<?php
    $terms_and_conditions = "<div>
      <h2>ACKNOWLEDGMENT</h2>
      <p>By selecting 'Opt In' to this Black Bear Energy Request For Proposal ('RFP'), Channel Partner acknowledges and agrees that:</p>
      <ol>
        <li><u><b>Black Bear Energy Fee:</b></u>  With regard to the properties listed in the RFP, Black Bear Energy is acting as energy development representative and advisor to the property owner/tenant ('Client') and Channel Partner agrees that it will pay Black Bear Energy certain fees as detailed in <u>Exhibit A</u> below ('BBE Project Fee') if Channel Partner is awarded business by Client.  BBE Project Fee shall be due upon execution of definitive agreements by Channel Partner and Client.</li>
        <li><u><b>Non-Circumvention as to Properties listed in the RFP:</b></u>  With regard to the properties listed in the RFP, Channel Partner agrees not to attempt to circumvent the BBE Project Fee and to communicate all bids and offers through Black Bear Energy. Channel Partner shall notify Black Bear Energy if another party improperly contacts Channel Partner or suggests circumventing the BBE Project Fee.  With regards to the properties listed in the RFP, if Channel Partner contracts directly with Client without going through Black Bear Energy, Channel Partner may be suspended from future Black Bear Energy RFP solicitations and may be liable to Black Bear Energy for the BBE Project Fee as set forth in both <u>Exhibit A</u> and the Black Bear Energy and Client engagement agreement.  This Section 2 does not restrict Channel Partner from contacting Client about other properties not listed in the RFP.  The obligations within this Section 2 shall expire one (1) year after the expiration or earlier termination of Black Bear Energy’s formal engagement with Client. </li>
        <li><u><b>Channel Partner Authorization:</b></u>  The individual Opting In to the RFP and submitting a proposal is authorized by Channel Partner to make representations and to obligate Channel Partner to perform the commitments contained in its proposal and in this Acknowledgement.</li>
        <li><u><b>Acceptance of Terms and Conditions:</b></u>  Opting into the RFP and submitting a response indicates Channel Partner’s acceptance of the terms and conditions contained in the RFP, RFP Appendix, and Bid Submission Form unless <u>clearly and specifically noted otherwise</u> in the 'Notes' section of the Black Bear Energy Portal.  Failure to comply with this Section 4 may result in a withdrawal of award to Channel Partner, if applicable, and a disqualification of Channel Partner’s proposal from further consideration.</li>
        <li><u><b>RFP Response Costs:</b></u>  Black Bear Energy accepts no financial responsibility for any costs incurred by Channel Partner in responding to this Acknowledgement and RFP.</li>
        <li><u><b>RFP Modification:</b></u>  Black Bear Energy, in its sole and absolute discretion, reserves the right to cancel or to modify the RFP including any documents attached thereto.  However, Black Bear Energy shall notify Channel Partner of any cancellation or modifications in a timely manner.</li>
        <li><u><b>Inquiries and Communications regarding RFP Acknowledgement:</b></u>  Inquiries regarding this Acknowledgement should be directed via email to <a href='mailto:RFP@blackbearenergy.com'>RFP@blackbearenergy.com</a>.  </li>
        <li><u><b>No Guarantee:</b></u>  Black Bear Energy does not guarantee that any of the submissions from the RFP will be selected.  Any award of business is at the sole discretion of the Client.  </li>
    </ol>   
      <h2><u>EXHIBIT A</u></h2>
      <h3>BLACK BEAR PROJECT FEE SCHEDULE</h3>
        <p>The BBE Project Fee shall consist of the Project Fee and the Carry Fee as set forth below.  </p>
        <p>Unless otherwise agreed in writing, the <b><i>'Project Fee'</i></b> shall be an amount in cash equal to: 1) ten cents per watt ($0.10/W) of the dc photovoltaic capacity for a Project, 2) five cents per watt hour ($0.05/Wh) of the energy storage capacity, 3) fifty cents per watt ($0.50/W) of the energy reduced (capped at year 1 estimated annual savings) for LED lighting improvements, and 4) five percent (5%) of the total capital cost wind or any other renewable energy or clean tech solution other than photovoltaic on a Project.  Both parties recognize that Project Fees may be earned if several type of projects [1), 2), 3) and/or 4)] exist at one site.   One-half of the Project Fee shall be due and payable by wire transfer at the execution of definitive agreements between Client and Channel Partner with respect to each such project and the other half of the Project Fee shall be due and payable by wire transfer at Commencement of Construction (as defined below) with respect to each such project.</p>
        <p><b><i>Commencement of Construction</i></b> shall mean and shall be deemed to have occurred, with respect to each project, when all pre-construction engineering and design work has been completed and all necessary licenses, permits and approvals have been received such that physical construction of the project may begin.</p>
        <p>The <b><i>'Carry Fee'</i></b> with respect to each project shall be an amount in cash equal to two percent (2%) of the gross revenue from such project determined without any setoff or deduction with respect to the operations of such Project.  The Carry Fee shall be payable on an annual basis commencing on the anniversary of the Commercial Operation Date and ending upon the final decommission of the project.</p>
        <p><b><i>Commercial Operation Date</i></b> shall mean and shall be deemed to have occurred, with respect to each project, when (i) all necessary licenses, permits and approvals have been obtained in compliance with all legal requirements for the project, (ii) the project system has been installed in accordance with all legal requirements and connected to the distribution system for the local utility and/or to tenants, if applicable, (iii) the project has begun to deliver electricity on a continuous basis, if applicable, (iv) all related facilities and rights, if any, have been completed or obtained to allow regular operation of the project, and (v) if applicable and to the extent required, the local utility has approved interconnection with the distribution system to allow regular operation of the project. </p>
        
  
    </div>";
?>